version: "3.5"
services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    environment:
      SA_PASSWORD: Sample_passw0rd!
      ACCEPT_EULA: Y
    ports:
      - "14333:1433"
      
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports: 
      - "10000:10000" 
      - "10001:10001"

  backend:
    build:
      context: .
      dockerfile: Src/WebUI/Dockerfile
    env_file:
      - .env
    ports:
      - "4500:80"
    depends_on:
      - db
      - storage
